---
title: "Tidying Data in R"
author: "Amanda Moors"
date: "August 15, 2018"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

Read in libraries

```{r, warning = F, message = F, echo = T}
library(dplyr)
library(tidyr)

```

Read in data from [Mike Byerly. 2016. Alaska commercial salmon catches by management region (1886- 1997). Gulf of Alaska Data Portal. df35b.304.2.](https://knb.ecoinformatics.org/#view/df35b.304.2)

```{r}
catch_df <- read.csv(url("https://knb.ecoinformatics.org/knb/d1/mn/v2/object/df35b.302.1", method = "libcurl"),
                    stringsAsFactors = FALSE)
head(catch_df)
```

```{r}
catch_df <-catch_df %>% 
  select(-All, -notesRegCode)
  # select positively by name
  # eg: select(Region, Year, Chinook...)
head(catch_df)
```

```{r}
catch_df <- catch_df %>% 
  gather(key = "species", value =  "catch", -Region, -Year) %>% 
  rename(catch_thousands = catch)

head(catch_df)


```


```{r}
catch_ingergers <- as.integer(catch_df$catch_thousands)

i <- which(is.na(catch_ingergers) ==T)

catch_df$catch_thousands[i]

head(catch_df)

```


1) Turn "I" into 1 in the catch_thousands column
2) coerce catch_thousands into integer type
3) convert catch_thousands to catch

```{r}
catch_df <- catch_df %>% 
  mutate(catch_thousands = ifelse(catch_thousands == "I", 1, catch_thousands)) %>% 
  mutate(catch_thousands = as.integer(catch_thousands)) %>% 
  mutate(catch = catch_thousands*1000)


tail(catch_df)
```


